 -- PARAMETER OVERRIDE VALUES --

 -- Framework\Parent.dtsx\CM.SSISDB.ConnectionString_0 Package Parameter Override
Declare @PackageParameter_CM_SSISDB_ConnectionString_0 sql_variant = N'Data Source=vSql2014\FwCe2;Initial Catalog=SSISDB;Integrated Security=True;Application Name=SSIS-Parent-SSISDB;'
Declare @PackageParameter_CM_SSISFrameworkDB_ConnectionString_1 sql_variant = N'Data Source=vSql2014\FwCe2;Initial Catalog=SSISFrameworkDB;Integrated Security=True;Application Name=SSIS-Parent-SSISDB;'

 -------------------------------

/*
Script Name: E:\Andy\_20170714\vmSql16_FwCommunity\Framework\3_vmSql16-FwCommunity_SSISDB_Framework_Framework.overrides.sql
Generated From Catalog Instance: vmSql16\FwCommunity
Catalog Name: SSISDB
Folder Name: SSIS
Project Name: Framework
Generated By: VMSQL16\A. Ray Leonard
Generated Date: 7/14/2017 7:00:03 AM
Generated From: CatalogBase v2.0.2.0 executing on: VMSQL16
*/

print 'Script Name: E:\Andy\_20170714\vmSql16_FwCommunity\Framework\3_vmSql16-FwCommunity_SSISDB_Framework_Framework.overrides.sql
Generated From Catalog Instance: vmSql16\FwCommunity
Catalog Name: SSISDB
Folder Name: SSIS
Project Name: Framework
Generated By: VMSQL16\A. Ray Leonard
Generated Date: 7/14/2017 7:00:03 AM
Generated From: CatalogBase v2.0.2.0 executing on: VMSQL16'
print ''
print '------------------------------------------------------------'
print 'Deployed to Instance: ' + @@servername
print 'Deploy Date: ' + Convert(varchar,GetDate(), 101) + ' ' + Convert(varchar,GetDate(), 108)
print 'Deployed By: ' + original_login()
print '------------------------------------------------------------'
print ''

declare @ParentPackageOverridesErrMsg varchar(100) 

print 'Check for folder: SSIS ' 
If Not Exists(Select name 
              From SSISDB.[catalog].folders 
              Where name = N'SSIS') 
 begin 
  set @ParentPackageOverridesErrMsg = ' - SSIS folder does not exist.' 
  raisError(@ParentPackageOverridesErrMsg, 16, 1) 
  return 
 end 
Else 
 begin 
  print ' - SSIS folder exists.' 
 end 
print '' 
 
print 'Check for project: Framework ' 
If Not Exists(Select name 
              From SSISDB.[catalog].projects 
              Where name = N'Framework') 
 begin 
  set @ParentPackageOverridesErrMsg = ' - Framework project does not exist.' 
  raisError(@ParentPackageOverridesErrMsg, 16, 1) 
  return 
 end 
Else 
 begin 
  print ' - Framework project exists.' 
 end 
print '' 



 -- Framework\Parent.dtsx\CM.SSISDB.ADONet.ConnectionString Package Parameter Override
print 'Framework\Parent.dtsx\CM.SSISDB.ADONet.ConnectionString Package Parameter Override'
print ' - Clear CM.SSISDB.ADONet.ConnectionString Package Parameter Override or Reference'
Exec [SSISDB].[catalog].[clear_object_parameter_value] 
     @object_type = 30 -- package 
   , @object_name = N'Parent.dtsx' 
   , @parameter_name = N'CM.SSISDB.ADONet.ConnectionString' 
   , @folder_name = N'SSIS' 
   , @project_name = N'Framework' 
print ' - Framework\Parent.dtsx\CM.SSISDB.ADONet.ConnectionString Package Parameter Override cleared'
print ''

print ' - Add or Update CM.SSISDB.ADONet.ConnectionString Package Parameter Override'
Exec [SSISDB].[catalog].[set_object_parameter_value] 
     @object_type = 30 -- package 
   , @parameter_name = N'CM.SSISDB.ADONet.ConnectionString' 
   , @object_name = N'Parent.dtsx' 
   , @folder_name = N'SSIS' 
   , @project_name = N'Framework' 
   , @parameter_value = @PackageParameter_CM_SSISDB_ConnectionString_0
   , @value_type = 'V' 
print ' - Framework\Parent.dtsx\CM.SSISDB.ADONet.ConnectionString Package Parameter Override added / updated'
print ''



 -- Framework\Parent.dtsx\CM.SSISFrameworkDB.ADONet.ConnectionString Package Parameter Override
print 'Framework\Parent.dtsx\CM.SSISFrameworkDB.ADONet.ConnectionString Package Parameter Override'
print ' - Clear CM.SSISFrameworkDB.ADONet.ConnectionString Package Parameter Override or Reference'
Exec [SSISDB].[catalog].[clear_object_parameter_value] 
     @object_type = 30 -- package 
   , @object_name = N'Parent.dtsx' 
   , @parameter_name = N'CM.SSISFrameworkDB.ADONet.ConnectionString' 
   , @folder_name = N'SSIS' 
   , @project_name = N'Framework' 
print ' - Framework\Parent.dtsx\CM.SSISFrameworkDB.ADONet.ConnectionString Package Parameter Override cleared'
print ''

print ' - Add or Update CM.SSISFrameworkDB.ADONet.ConnectionString Package Parameter Override'
Exec [SSISDB].[catalog].[set_object_parameter_value] 
     @object_type = 30 -- package 
   , @parameter_name = N'CM.SSISFrameworkDB.ADONet.ConnectionString' 
   , @object_name = N'Parent.dtsx' 
   , @folder_name = N'SSIS' 
   , @project_name = N'Framework' 
   , @parameter_value = @PackageParameter_CM_SSISFrameworkDB_ConnectionString_1
   , @value_type = 'V' 
print ' - Framework\Parent.dtsx\CM.SSISFrameworkDB.ADONet.ConnectionString Package Parameter Override added / updated'
print ''
